### ISSUE TITLE
Compton-y maps for tSZ

### ISSUE THREAD

**Issue by nehapjoshi** [yomori/Agora-docs#6]
Hi,

Are compton-y maps available for lensed tSZ? On globus I see one file for lensed tSZ and the docs say that this should be a T map. 

Thanks,
Neha

**Comment by yomori** [comment]
Hi Neha,
Sorry for the delayed response. The products in `/components/tsz/len/ `are actually Compton-y maps. Admittedly, I think the documentation was confusing -- what I actually meant was that the map is stored in field=0 (where T is usually stored) of HEALPix fits format. I've updated the description. Thank you for bringing this up.
